FORMAT: 1A

# Techo Api

# Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "destacados": "/destacados",
            "video": "/video",
            "viviendas":"/viviendas"
        }

# GET /destacados

+ Response 200 (application/json)
        [
        {
            "id": "1",
            "talent_name": "hago dibujitos",
            "user":"brunancio",
            "visit_counter":372,
            "talent_small_image":"talent1img.png",
            "talent_user_avatar":"http://d3mrnpbbo94dn5.cloudfront.net/uploads/user/avatar/3968/default_foto_carnet_Patricia.jpg" 
            },
{
            "id": "2",
            "talent_name": "Actúo, canto y soy mamá",
            "user":"Lulopilato",
            "visit_counter":373,
            "talent_small_image":"talent1img.png",
            "talent_user_avatar":"http://portal.unedmotril.org/files/avatares/picture-8580.jpg" 
            }
{
            "id": "3",
            "talent_name": "Historietas y misterio",
            "user":"Liniers",
            "visit_counter":373,
            "talent_small_image":"talent1img.png",
            "talent_user_avatar":"http://www.fulltv.com.ar/images/peliculas/actoresm/maurice-benard.jpg" 
            }
{
            "id": "4",
            "talent_name": "Fotos y cosha golda",
            "user":"Sebastián B",
            "visit_counter":373,
            "talent_small_image":"talent1img.png",
            "talent_user_avatar":"http://www.solucionesong.org/img/usuarios/543d662ec52dd/thumb.very_small.foto_carnet_20142.jpg" 
            }
{
            "id": "5",
            "talent_name": "Powerpointeamos",
            "user":"PMF",
            "visit_counter":373,
            "talent_small_image":"talent1img.png",
            "talent_user_avatar":"http://2.bp.blogspot.com/-Rc9VQvnI-Fk/VHNqzeMLDmI/AAAAAAAAC8g/dHz-wdtcdhg/s45/joco_carnet.jpg" 
            }
]
            
# GET /video

+ Response 200 (application/json)

        {
            "url": "https://www.youtube.com/watch?v=QlPyunEHqdI"
            }
            
# GET /viviendas

+ Response 200 (application/json)

        {
            "cantidad": "21"
            }
