FORMAT: 1A

# Techo Api

# Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "destacados": "/destacados",
            "video": "/video",
            "viviendas":"/viviendas"
        }

# GET /destacados

+ Response 200 (application/json)

        {
            "id": "1",
            "talent_name": "hago dibujitos",
            "user":"brunancio",
            "visit_counter":372,
            "talent_small_image":"talent1img.png",
            "talent_user_avatar":"avatar1.png" ==> si la cuenta del talento esta asociada a una red social??
            }
            
# GET /video

+ Response 200 (application/json)

        {
            "url": "https://www.youtube.com/watch?v=QlPyunEHqdI",
            }
            
# GET /viviendas

+ Response 200 (application/json)

        {
            "cantidad": "21",
            }
