FORMAT: 1A

# Techo Api

# Retrieve the Entry Point [GET]

+ Response 200 (application/json)
        {
            "destacados": "/destacados",
            "video": "/video",
            "viviendas":"/viviendas"
            "galeria/1":"/galeria/1"
            "galeria/2":"/galeria/2"
        }

# GET /destacados

+ Response 200 (application/json)

        [
        {
            "id": "1",
            "talent_name": "hago dibujitos",
            "user":"brunancio",
            "visit_counter":372,
            "talent_small_image":"https://x2.xingassets.com/image/d_5_4_6fff615da_12210765_2/christian-carnet-foto.256x256.jpg",
            "talent_user_avatar":"http://d3mrnpbbo94dn5.cloudfront.net/uploads/user/avatar/3968/default_foto_carnet_Patricia.jpg" 
            },
        {
            "id": "2",
            "talent_name": "Actuo, canto y soy mama",
            "user":"Lulopilato",
            "visit_counter":373,
            "talent_small_image":"https://x1.xingassets.com/image/6_2_7_4a76ce0be_7065054_9/vanessa-carnet-fuchs-foto.256x256.jpg",
            "talent_user_avatar":"http://portal.unedmotril.org/files/avatares/picture-8580.jpg" 
            },
        {
            "id": "3",
            "talent_name": "Historietas y misterio",
            "user":"Liniers",
            "visit_counter":373,
            "talent_small_image":"http://www.acvweb.com/images/CARNET-FOTO-PEPE-ARDERIU.jpg",
            "talent_user_avatar":"http://www.fulltv.com.ar/images/peliculas/actoresm/maurice-benard.jpg" 
            },
        {
            "id": "4",
            "talent_name": "Fotos y cosha golda",
            "user":"Sebastian B",
            "visit_counter":373,
            "talent_small_image":"https://x2.xingassets.com/image/e_1_b_4c2678856_15518751_1/oscar-quintanilla-morales-foto.256x256.jpg",
            "talent_user_avatar":"http://www.solucionesong.org/img/usuarios/543d662ec52dd/thumb.very_small.foto_carnet_20142.jpg" 
            },
        {
            "id": "5",
            "talent_name": "Powerpointeamos",
            "user":"PMF",
            "visit_counter":373,
            "talent_small_image":"https://x2.xingassets.com/image/0_7_6_e12eadd1d_5859267_4/angie-thomet-foto.256x256.jpg",
            "talent_user_avatar":"http://2.bp.blogspot.com/-Rc9VQvnI-Fk/VHNqzeMLDmI/AAAAAAAAC8g/dHz-wdtcdhg/s45/joco_carnet.jpg" 
            }
        ]
            
# GET /video

+ Response 200 (application/json)

        {
            "url": "https://www.youtube.com/embed/QlPyunEHqdI"
            }
            
# GET /viviendas

+ Response 200 (application/json)

        {
            "cantidad": "21"
            }
            
# GET /galeria/1

+ Response 200 (application/json)

        [
        {
            "id": "1",
            "talent_name": "hago dibujitos",
            "user":"brunancio",
            "visit_counter":372,
            "talent_small_image":"https://x2.xingassets.com/image/d_5_4_6fff615da_12210765_2/christian-carnet-foto.256x256.jpg",
            "talent_user_avatar":"http://d3mrnpbbo94dn5.cloudfront.net/uploads/user/avatar/3968/default_foto_carnet_Patricia.jpg" 
            },
        {
            "id": "2",
            "talent_name": "Actuo, canto y soy mama",
            "user":"Lulopilato",
            "visit_counter":373,
            "talent_small_image":"https://x1.xingassets.com/image/6_2_7_4a76ce0be_7065054_9/vanessa-carnet-fuchs-foto.256x256.jpg",
            "talent_user_avatar":"http://portal.unedmotril.org/files/avatares/picture-8580.jpg" 
            },
        {
            "id": "3",
            "talent_name": "Historietas y misterio",
            "user":"Liniers",
            "visit_counter":373,
            "talent_small_image":"http://www.acvweb.com/images/CARNET-FOTO-PEPE-ARDERIU.jpg",
            "talent_user_avatar":"http://www.fulltv.com.ar/images/peliculas/actoresm/maurice-benard.jpg" 
            },
        {
            "id": "4",
            "talent_name": "Fotos y cosha golda",
            "user":"Sebastian B",
            "visit_counter":373,
            "talent_small_image":"https://x2.xingassets.com/image/e_1_b_4c2678856_15518751_1/oscar-quintanilla-morales-foto.256x256.jpg",
            "talent_user_avatar":"http://www.solucionesong.org/img/usuarios/543d662ec52dd/thumb.very_small.foto_carnet_20142.jpg" 
            },
        {
            "id": "5",
            "talent_name": "Powerpointeamos",
            "user":"PMF",
            "visit_counter":373,
            "talent_small_image":"https://x2.xingassets.com/image/0_7_6_e12eadd1d_5859267_4/angie-thomet-foto.256x256.jpg",
            "talent_user_avatar":"http://2.bp.blogspot.com/-Rc9VQvnI-Fk/VHNqzeMLDmI/AAAAAAAAC8g/dHz-wdtcdhg/s45/joco_carnet.jpg" 
            }
        ]
        
# GET /galeria/2

+ Response 200 (application/json)

        [
        {
            "id": "16",
            "talent_name": "hago dibujitos",
            "user":"brunancio",
            "visit_counter":372,
            "talent_small_image":"https://x2.xingassets.com/image/d_5_4_6fff615da_12210765_2/christian-carnet-foto.256x256.jpg",
            "talent_user_avatar":"http://d3mrnpbbo94dn5.cloudfront.net/uploads/user/avatar/3968/default_foto_carnet_Patricia.jpg" 
            },
        {
            "id": "17",
            "talent_name": "Actuo, canto y soy mama",
            "user":"Lulopilato",
            "visit_counter":373,
            "talent_small_image":"https://x1.xingassets.com/image/6_2_7_4a76ce0be_7065054_9/vanessa-carnet-fuchs-foto.256x256.jpg",
            "talent_user_avatar":"http://portal.unedmotril.org/files/avatares/picture-8580.jpg" 
            },
        {
            "id": "18",
            "talent_name": "Historietas y misterio",
            "user":"Liniers",
            "visit_counter":373,
            "talent_small_image":"http://www.acvweb.com/images/CARNET-FOTO-PEPE-ARDERIU.jpg",
            "talent_user_avatar":"http://www.fulltv.com.ar/images/peliculas/actoresm/maurice-benard.jpg" 
            },
        {
            "id": "19",
            "talent_name": "Fotos y cosha golda",
            "user":"Sebastian B",
            "visit_counter":373,
            "talent_small_image":"https://x2.xingassets.com/image/e_1_b_4c2678856_15518751_1/oscar-quintanilla-morales-foto.256x256.jpg",
            "talent_user_avatar":"http://www.solucionesong.org/img/usuarios/543d662ec52dd/thumb.very_small.foto_carnet_20142.jpg" 
            },
        {
            "id": "20",
            "talent_name": "Powerpointeamos",
            "user":"PMF",
            "visit_counter":373,
            "talent_small_image":"https://x2.xingassets.com/image/0_7_6_e12eadd1d_5859267_4/angie-thomet-foto.256x256.jpg",
            "talent_user_avatar":"http://2.bp.blogspot.com/-Rc9VQvnI-Fk/VHNqzeMLDmI/AAAAAAAAC8g/dHz-wdtcdhg/s45/joco_carnet.jpg" 
            }
        ]
